name: C/C++ CI

on: 
  push:
    branches: 
      - eth
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ./configure
      working-directory: ./hashing
