name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1 
    - name: make check
      run: ./hashing/make
    - name: run test
      run: ./hashing/./runUnitTests 

